# Docs: https://docs.github.com/en/code-security/supply-chain-security/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    labels:
      - 'github-actions'
    reviewers:
      - 'jerome-benoit'
      - 'olivierbagot'
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    groups:
      regular:
        update-types:
          - 'patch'
          - 'minor'
        exclude-patterns:
          - 'typescript'
      typescript:
        update-types:
          - 'patch'
          - 'minor'
          - 'major'
        patterns:
          - 'typescript'
      eslint:
        update-types:
          - 'major'
        patterns:
          - 'eslint'
          - '@eslint/*'
      mikro-orm:
        patterns:
          - '@mikro-orm/*'
      commitlint:
        patterns:
          - '@commitlint/*'
      vitest:
        patterns:
          - 'vitest'
          - '@vitest/*'
      vite:
        patterns:
          - 'vite'
          - '@vitejs/*'
    labels:
      - 'dependencies'
    reviewers:
      - 'jerome-benoit'
      - 'olivierbagot'
    versioning-strategy: increase
  - package-ecosystem: pip
    directory: 'tests/ocpp-server'
    schedule:
      interval: daily
    groups:
      regular:
        update-types:
          - 'patch'
          - 'minor'
    labels:
      - 'dependencies'
    reviewers:
      - 'jerome-benoit'
      - 'olivierbagot'
  - package-ecosystem: docker
    directories:
      - '/docker'
      - '/ui/web/docker'
    schedule:
      interval: daily
    labels:
      - 'docker'
    reviewers:
      - 'jerome-benoit'
      - 'olivierbagot'
